In [13]:
# Source - https://stackoverflow.com/a/5399339
# Posted by pv., modified by community. See post 'Timeline' for change history
# Retrieved 2026-06-23, License - CC BY-SA 4.0

%load_ext autoreload
%autoreload 2

from scipy.stats import chi2
from heritage import *
from hawkes_multivariate_patch import *


In [14]:
import numpy as np

times = np.array([
    0.10,
    0.25,
    0.31,
    0.55,
    0.78,
    1.05,
    1.12,
    1.30,
    1.75,
    2.10,
    2.35,
    2.90,
    3.15,
    3.40,
    3.95,
    4.10,
    4.55,
    5.00,
    5.30,
    5.85
], dtype=float)

types = np.array([
    0,
    1,
    0,
    2,
    1,
    0,
    0,
    2,
    1,
    1,
    0,
    2,
    0,
    1,
    2,
    0,
    1,
    0,
    2,
    1
], dtype=int)

T = 6.0
d = 3

In [22]:
model = MultivariateHawkesMLE(
    n_types=d,
    beta_init=1.0,
    max_iter=3000,
    tol=1e-8,
    n_starts=3,
    random_state=123,
)

model.fit(
    events=times,
    types=types,
    end_times=T,
)

params = model.get_params()

print(params["mu"])
print(params["alpha"])
print(params["beta"])
print(params["branching_ratio"])
print(params["is_stable"])

B shape :  (3, 3)
[1. 1. 1.]
----
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
(3, 3)
----
B shape :  (3, 3)
[1. 1. 1.]
----
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
(3, 3)
----
B shape :  (3, 3)
[1. 1. 1.]
----
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
(3, 3)
----
B shape :  (3, 3)
[1. 1. 1.]
----
[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
(3, 3)
----
B shape :  (3, 3)
[1. 1. 1.]
----
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
(3, 3)
----
B shape :  (3, 3)
[1. 1. 1.]
----
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
(3, 3)
----
B shape :  (3, 3)
[1. 1. 1.]
----
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
(3, 3)
----
B shape :  (3, 3)
[1. 1. 1.]
----
[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
(3, 3)
----
B shape :  (3, 3)
[1. 1. 1.]
----
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
(3, 3)
----
B shape :  (3, 3)
[1. 1. 1.]
----
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
(3, 3)
----
B shape :  (3, 3)
[1. 1. 1.]
----
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
(3, 3)
----
B shape :  (3, 3)
[1. 1. 1.]
----
[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
(3, 3)
----
B sh